### ISSUE TITLE
[Filter Menu] Highlights

### ISSUE THREAD

**Issue by lavrton** [2bitcoder/Jquery-Gantt#10]
will highlight rows with a color depending on the selected criteria

**Comment by 2bitcoder** [comment]
selecting a highlight will highlight each gantt row (left panel) that meet the below criteria.

This will be a select list with the following options

Backlog                                                                - Highlight Color :  #D2D2D9
Ready                                                                    - Highlight Color :  #B2D1F0
In Progress                                                         - Highlight Color : #66A3E0
Complete                                                            - Highlight Color :  #99C299
Late Tasks                                                          - Highlight Color :  #FFB2B2
Due Tasks                                                          - Highlight Color :  #FFC299
Milestones                                                         - Highlight Color :  #D6C2FF
Deliverables                                                     - Highlight Color :  #E0D1C2
Financial Markers                                         - Highlight Color :  #F0E0B2
Timesheets Tasks                                         - Highlight Color :  #C2C2B2
Reportable Tasks                                         - Highlight Color :  #E0C2C2
Health                                                                 - Highlight Color:  Red, Amber, Green 
(Taken from the Health data item)

(Taken from the Status data item)
Backlog
Ready
In Progress
Complete
