### ISSUE TITLE
Dependency - Removing

### ISSUE THREAD

**Issue by 2bitcoder** [2bitcoder/Jquery-Gantt#106]
Since the introduction of multiple dependencies removing task dependencies has stopped functioning correctly.

The old way of deleting was to drag the dependency line into an open space.  This no longer works.

Need to find a better way of removal.  - Suggestion as per picture is to use X on mouse over you delete dependency.

![image](https://cloud.githubusercontent.com/assets/8335038/15097427/4a0dd216-155e-11e6-93d0-dc8df9ab6324.png)

**Comment by lavrton** [comment]
<img width="493" alt="screen shot 2016-05-24 at 11 40 16" src="https://cloud.githubusercontent.com/assets/1443320/15492326/58a43cdc-21a4-11e6-976e-ce87345e961b.png">

This button will remove all dependencies.
