### ISSUE TITLE
Some Dates Displayed in Gantt Editor - are different to what is saved in the database

### ISSUE THREAD

**Issue by 2bitcoder** [2bitcoder/Jquery-Gantt#107]
The dates shown in gantt are +1 Day from what is received through REST calls.  Also on saving dates are -1 Day.

So the gantt always shows the wrong date by 1 day.

![image](https://cloud.githubusercontent.com/assets/8335038/15097645/0b78dc38-1565-11e6-9bf4-2f10eddac15f.png)

**Comment by 2bitcoder** [comment]
I have also checked the JSON data to make sure the request is not serving up the wrong dates

here is the json for 'Stage 5 - Decommission and Close'  as you can see the dates match the status report but not the gantt editor.  

{  
      "acttimesheet":null,
      "color":"#0090d3",
      "darkcolor":null,
      "deliverable":true,
      "depend":"",
      "description":"",
      "end":"2016-07-08T01:00:00",
      "b_end":"2016-07-08T01:00:00",
      "financial":false,
      "health":21,
      "id":2434,
      "name":"Stage 5 - Decommission and Close",
      "lightcolor":null,
      "milestone":false,
      "parentid":0,
      "sitekey":"4f06759f4d9e7957",
      "complete":0,
      "ProjectRef":334,
      "reportable":true,
      "ResID":null,
      "Resources":[  

      ],
      "sortindex":33.0,
      "start":"2016-07-05T01:00:00",
      "b_start":"2016-07-05T01:00:00",
      "status":110,
      "timesheet":null,
      "WBS_ID":409,
      "wbstsid":2434,
      "wo":2,
      "Comments":0
   },

**Comment by lavrton** [comment]
Te issue is "fixed". But if fact the behaviour is correct.

There was time zone problem. 
`2016-08-30T14:00:00Z` - is UTC time. This date will be `2016-08-31` in your timezone (and it is not in my current timezone). I fixed it by displaying UTC dates (not local). Is it ok?

**Comment by 2bitcoder** [comment]
Will the dates be correct for everyone world wide or will there still be an issue depending on geographic  location?

**Comment by lavrton** [comment]
Should be NO issues. Everyone will see the app as if they are in UTC timezone.

**Comment by 2bitcoder** [comment]
Awesome - Thank you
