### ISSUE TITLE
[Filter Menu] Filters

### ISSUE THREAD

**Issue by lavrton** [2bitcoder/Jquery-Gantt#11]
Will filter displayed rows depending on the selected criteria

**Comment by 2bitcoder** [comment]
selecting a filter will filter each gantt row (left & right panels) that meet the below criteria.    eg hide everything else that does meet the criteria.

This will be a select list with the following options

Status - Backlog                                                                
Status - Ready                                                                   
Status - In Progress                                                        
Status - Complete                                                            
Late Tasks      (tasks that are past due)    End Date < Now                                                  
Due Tasks      (tasks due in the next 2 weeks) End Date between now and - 2 weeks)                                                  
Milestones                                                         
Deliverables                                                     
Financial Markers                                         
Timesheets Tasks                                         
Reportable Tasks                                         
Health - Red
Health - Amber
Health - Green                                                                 
(Taken from the Health data item)

(Taken from the Status data item)
Backlog
Ready
In Progress
Complete
