### ISSUE TITLE
[Tasks] Properties contextMenu option will load modal with iframe loaded with additional  information on task from server

### ISSUE THREAD

**Issue by lavrton** [2bitcoder/Jquery-Gantt#18]

**Comment by 2bitcoder** [comment]
selecting the properties box will open a modal window with extended information about the task.

screen shots added:   the data can be created from the supplied (enhanced) data model,  no need for a iframe now.

**Comment by 2bitcoder** [comment]
![modal2](https://cloud.githubusercontent.com/assets/8335038/5678547/c9cfa082-9847-11e4-8120-4dcbab337b1d.png)
![modal1](https://cloud.githubusercontent.com/assets/8335038/5678548/cc70746a-9847-11e4-88dd-c7d08870b75c.png)

**Comment by lavrton** [comment]
What is "order" property in modal menu?

I need more info how "Work Order" data is looking (there is only one row in JSON example)

**Comment by 2bitcoder** [comment]
Hello Anton,

A work order is a select list  eg

                <select class="selectfields" id="edit-WO" name="WO"
style="width:200px;">                    <option value=""></option>
                            <option value="307">WO10302</option>
                         <option value="43"
selected="selected">WO10000</option>                </select>


Each task can be assigned to a work order,  it will be the same as Status
and Health, I will need to supply the work orders via a json file as they
will be different for each project.

A work order links the task to a financial marker in my system.

Hope that make sense...

Regards

Greg





On Wed, Jan 21, 2015 at 5:56 PM, Anton Lavrenov <notifications@github.com>
wrote:

> What is "order" property in modal menu?
>
> I need more info how "Work Order" data is looking (there is only one row
> in JSON example)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/2bitcoder/Jquery-Gantt/issues/18#issuecomment-70792816>
> .
>



-- 

Regards

Greg Vandeligt

*Director*
*Level35 Pty Ltd*

Website: www.level35.net
OneView PPM: demo.oneviewapps.com

Email: gvandeligt@oneviewapps.com
Mobile: +61430 017 771
