### ISSUE TITLE
[Gantt View] Add ability to add multiple resources to a task

### ISSUE THREAD

**Issue by lavrton** [2bitcoder/Jquery-Gantt#24]

**Comment by 2bitcoder** [comment]
Add ability to add multiple resources to a task.

I'll write an API to supply the resource 'name' and 'ID's that are available to the project  (json list).
eg:  /api/resourcelist/43/177/2b00da46b57c0395
[{ ID: 1,  Name: Joe Black, JobTitle: Programmer}, { ID: 1,  Name: Fred Bloggs, JobTitle: Accountant}]

I'll write an API to get the resources allocated to each task
eg:  /api/resourcetotasks/43/177/2b00da46b57c0395      (REST)
[{
taskid: 1024,
Resources: [{ ID: 1,  Name: Joe Black}, { ID: 1,  Name: Fred Bloggs}]
}]

As per the video -> click on an icon to open a model and select the resources to added to each task

**Comment by lavrton** [comment]
https://www.youtube.com/watch?v=4_-OitAHCkE
