### ISSUE TITLE
Task rows alignment with gantt rows

### ISSUE THREAD

**Issue by 2bitcoder** [2bitcoder/Jquery-Gantt#67]
Change the current model as any font size change breaks the alignment between the 2 panels  (task and gantt).  Maybe move to a table on the task panel as it may be easier to align the table rows and gantt rows.

**Comment by lavrton** [comment]
I just set `max-height` property for tasks in side panel (currently 21px).

I think calculation height from side panel then pass that value to chart is not good way.
So I close issue for now.
