### ISSUE TITLE
Zooming: Week  -  Expanding the task panel pushes gantt panel further right 

### ISSUE THREAD

**Issue by 2bitcoder** [2bitcoder/Jquery-Gantt#68]
To much space is left between the start of the gantt and the task list when the task list is expanded right and collapsed left.

**Comment by lavrton** [comment]
Need more info. Can not reproduce.

**Comment by 2bitcoder** [comment]
this video shows the issue better

https://www.youtube.com/watch?v=5LJjvkCTlp4&feature=youtu.be
