### ISSUE TITLE
[MS Project Menu] Upload new project

### ISSUE THREAD

**Issue by lavrton** [2bitcoder/Jquery-Gantt#8]
Will open a modal with a drag and drop area for a file msproject.xml file. When file is dropped the xml contents are read into a javascript object and then written to the database.

Ajax call to a .cshtml page passing through parameters for each row.

**Comment by 2bitcoder** [comment]
create new rows automatically from a microsoft project plan .xml file.   same sent via skype   here is my code that filtered and imported a ms project plan - this function should create new items for all records not filter most out.

we will need to find the xml items that is equivalent to parent and dependency, to handle grouping and dependencies across tasks

<script>


    $("#filename").change(function (e) {
        var ext = $("input#filename").val().split(".").pop().toLowerCase();

        if ($.inArray(ext, ["xml"]) == -1) {
            alert('Upload xml');
            return false;
        }

        function parseXML(xml) {
            //console.log(xml);
            var rowno = 1;
            var $task = $(xml).find('FieldID').filter(function () {
                return $(this).text() == "188744006";
            }).closest('task');
            $('#contents1').append('Starting Import - This may take a few minutes please wait...<br>').html;
            for (var i = 0; i < $task.length; i++) {
               
                // alert the result
                var uid = $task[i].getElementsByTagName('uid')[0].innerHTML;
                var name = $task[i].getElementsByTagName('name')[0].innerHTML;
                //var start = $task[i].getElementsByTagName('start')[0].innerHTML.substring(0, 10);
                var start = $task[i].getElementsByTagName('start')[0].innerHTML;
                var finish = $task[i].getElementsByTagName('finish')[0].innerHTML;
                var milestone = $task[i].getElementsByTagName('milestone')[0].innerHTML;
                var percent = $task[i].getElementsByTagName('percentcomplete')[0].innerHTML;

                $.ajax({
                    async: false,
                    type: "POST", url: '/Processing/Projects/Methods/postMSProject', data: { projectno: projectno(), wbsid: wbs(), 'action-type': "new", uid: uid, ItemName: name, StartDate: start, EndDate: finish, milestone: milestone, PercentComplete: percent, SortOrder: i, status:'@status.ID',health:'@health.ID' }, dataType: "text",
                    success: function (response) {
                        //alert(rowno);
                        // $('#contents1').html('Import Success on item' + name);
                        $('#contents1').append('Import Success on line ' + rowno + '<br>').html;
                        //$( '<p>Import Success on line '+ rowno + '<p>\r\n' ).appendTo( "#contents1" );
                        // $("#contents1").html('<div>Import Success on line '+ rowno + '</div>\r\n');
                       // $('#contents1').append('Import Success on line ' + rowno + '<br>').html;
                        rowno++;
                        //$('#contents').html(html);
                        //alert('Access Controls successfully copied');
                    },
                    error: function (response) {
                        $('#contents1').append('Import Failure on line ' + rowno + '<br>').html;
                        rowno++;
                        //html += '<td>Import failure on line '+rowno+'</td>\r\n';
                        //  $('#contents').html(html);
                        //alert(response.name);                                
                    }
                });


            }
            $('#contents1').append('Import Finished...').html;
        }

        //get file contents and send to parsexml
        if (e.target.files !=
            undefined) {
            var reader = new FileReader();

            reader.onload = function (e) {
                  parseXML(e.target.result)
            };
            reader.readAsText(e.target.files.item(0));

        }

        return false;

    });
</script>
