### ISSUE TITLE
MS Project Import - doesn't keep sequence

### ISSUE THREAD

**Issue by 2bitcoder** [2bitcoder/Jquery-Gantt#84]
Importing MS project plan the sequence of line items differ to the project plan layout.
Will send the example plan via skype when your ready to check it out.

**Comment by 2bitcoder** [comment]
I have 2 microsoft project plans where this happens for you to test with. Let me kmow when you are ready and I will send them through.

**Comment by lavrton** [comment]
Test. Is it correct now?
