### ISSUE TITLE
Dependencies - many to one relationship

### ISSUE THREAD

**Issue by 2bitcoder** [2bitcoder/Jquery-Gantt#90]
Currently does not save more than one -> one relationship, although on screen it allows users to have many to one relations between items.

(note: problem may be with rendering after refresh, rather than saving)
will add a screen shot to show.

**Comment by 2bitcoder** [comment]
The MS Project Import leaves dependency nodes unassigned when they are Many to 1.

**Comment by 2bitcoder** [comment]
![depend](https://cloud.githubusercontent.com/assets/8335038/9378390/76188310-4764-11e5-889c-ba1b5ac25a37.png)

This should describe it better

**Comment by lavrton** [comment]
Test now. I was not doing a lot of tests. But in general should work.
