### ISSUE TITLE
Fix GanttEditor export to MSProject xml

### ISSUE THREAD

**Issue by 2bitcoder** [2bitcoder/Jquery-Gantt#93]
<Tasks>       
 <Task>
 <UID>0</UID>    (should be the sequence number, 'sort order' of the task)
  <ID>0</ID>        (should be the sequence number, 'sort order' of the task)

  <ManualStart>2015-07-19T17:52:00.000Z</ManualStart>      format to be: 2015-07-19T17:52:00
<ManualFinish></ManualFinish>  (add task finish date:  if null then add start + 1 day)

<EarlyStart>2015-07-19T17:52:00.000Z0</EarlyStart>            format to be: 2015-07-19T17:52:00
<EarlyFinish></EarlyFinish>                  (add task finish date:  if null then add start + 1 day)
<LateStart>2015-07-19T17:52:00.000Z</LateStart>      format to be: 2015-07-19T17:52:00
<LateFinish></LateFinish>                    (add task finish date:  if null then add start + 1 day)

All dates should be in 2015-07-20T03:53:04   format

**Comment by lavrton** [comment]
Test
